const CATEGORIES={
	LOAD:'CATEGORIES_LOAD',
	LOAD_SUCCESS:'LOAD_CATEGORIES_SUCCESS',
	LOAD_FAIL:'LOAD_CATEGORIES_FAIL', 
}
const ITEMS ={
	LOAD:'ITEMs_LOAD',
	LOAD_SUCCESS:'LOAD_ITEMS_SUCCESS',
	LOAD_FAIL:'LOAD_ITEMS_FAIL',
	LOAD_SPECIFIC:'SPECIFIC_ITEMS'
}

export {CATEGORIES ,ITEMS}; 